use_frameworks!

platform :ios, '9.0'

target 'LzCheckNetTraceSDK_Example' do
  pod 'LzCheckNetTraceSDK', :path => '../'

  target 'LzCheckNetTraceSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
